name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          git \
          openjdk-11-jdk \
          zlib1g-dev \
          python3-pip \
          python3-venv \
          unzip \
          libssl-dev \
          libffi-dev

    - name: Install Buildozer and dependencies
      run: |
        pip install --upgrade pip
        pip install buildozer
        pip install cython==0.29.33
        pip install virtualenv

    - name: Run Buildozer
      run: |
        echo "[buildozer]" > ~/.buildozer/config.ini
        echo "log_level = 2" >> ~/.buildozer/config.ini
        echo "warn_on_root = 1" >> ~/.buildozer/config.ini
        buildozer -v android debug

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v3
      with:
        name: kasir-app
        path: bin/*.apk*
        if-no-files-found: warn
        retention-days: 7
