name: Build Android APK with Docker

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: |
        docker build -t kasir-app-builder .

    - name: Run build in container
      run: |
        mkdir -p bin
        docker run --rm \
          -v "$(pwd)/bin:/app/bin" \
          kasir-app-builder

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v3
      with:
        name: kasir-app
        path: bin/*.apk*
        if-no-files-found: warn
        retention-days: 7
