name: Build Kivy Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install Buildozer
      run: |
        pip install --upgrade pip
        pip install buildozer
        pip install Cython==0.29.33
        pip install virtualenv

    - name: Set up Android SDK
      run: |
        mkdir -p ~/.android
        touch ~/.android/repositories.cfg
        
        # Download and extract Android Command Line Tools
        wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip -O cmdline-tools.zip
        mkdir -p ~/android-sdk/cmdline-tools/latest
        unzip -q cmdline-tools.zip -d ~/android-sdk/cmdline-tools/latest
        
        # Set environment variables
        echo "ANDROID_SDK_ROOT=$HOME/android-sdk" >> $GITHUB_ENV
        echo "$HOME/android-sdk/cmdline-tools/latest/cmdline-tools/bin" >> $GITHUB_PATH
        
        # Accept licenses
        yes | ~/android-sdk/cmdline-tools/latest/cmdline-tools/bin/sdkmanager --sdk_root=$HOME/android-sdk --licenses
        
        # Install required SDK components
        ~/android-sdk/cmdline-tools/latest/cmdline-tools/bin/sdkmanager --sdk_root=$HOME/android-sdk \
          "platform-tools" \
          "platforms;android-30" \
          "build-tools;30.0.3" \
          "ndk;21.3.6528147"

    - name: Configure Buildozer
      run: |
        mkdir -p ~/.buildozer
        echo "[buildozer]" > ~/.buildozer/config.ini
        echo "log_level = 2" >> ~/.buildozer/config.ini
        echo "warn_on_root = 1" >> ~/.buildozer/config.ini
        
        # Update buildozer.spec with correct paths
        ANDROID_SDK_ROOT=$HOME/android-sdk
        ANDROID_NDK_HOME=$ANDROID_SDK_ROOT/ndk/21.3.6528147
        
        sed -i "s|^android.sdk_path = .*|android.sdk_path = $ANDROID_SDK_ROOT|" buildozer.spec
        sed -i "s|^android.ndk_path = .*|android.ndk_path = $ANDROID_NDK_HOME|" buildozer.spec

    - name: Build APK
      run: |
        export ANDROID_SDK_ROOT=$HOME/android-sdk
        export ANDROID_NDK_HOME=$ANDROID_SDK_ROOT/ndk/21.3.6528147
        export PATH=$PATH:$ANDROID_SDK_ROOT/platform-tools
        
        # Build the APK
        buildozer -v android debug

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: kasir-app
        path: |
          bin/*.apk
          bin/*.apk.*
        if-no-files-found: warn
        retention-days: 7
