name: Build Kivy Android APK with Docker

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
    - uses: actions/checkout@v3

    - name: Build with Docker
      run: |
        # Pull the pre-built Kivy Docker image
        docker pull kivy/buildozer:latest
        
        # Create necessary directories
        mkdir -p ~/.buildozer
        mkdir -p ~/.android
        
        # Run the build in the Docker container
        docker run --rm \
          -v "${{ github.workspace }}:/app" \
          -v "${{ github.workspace }}/.buildozer:/root/.buildozer" \
          -v "${{ github.workspace }}/.android:/root/.android" \
          kivy/buildozer:latest \
          /bin/bash -c "cd /app && buildozer -v android debug"

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: kasir-app
        path: |
          bin/*.apk
          bin/*.apk.*
        if-no-files-found: warn
        retention-days: 7
